/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function P(a){"@babel/helpers - typeof";return P="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(d){return typeof d}:function(d){return d&&"function"==typeof Symbol&&d.constructor===Symbol&&d!==Symbol.prototype?"symbol":typeof d},P(a)}function F(){console.error.apply(console,arguments)}function fd(){console.warn.apply(console,arguments)}function gd(){if(gc)return $a.exports;gc=1;(function(a,d){(function(f,g){a.exports=g()})(hd,function(){function f(r){return r.charAt(0).toUpperCase()+
r.substring(1)}function g(r){return function(){return this[r]}}function k(r){if(r)for(var t=0;t<v.length;t++)if(void 0!==r[v[t]])this["set"+f(v[t])](r[v[t]])}var q=["isConstructor","isEval","isNative","isToplevel"],n=["columnNumber","lineNumber"],p=["fileName","functionName","source"],v=q.concat(n,p,["args"],["evalOrigin"]);k.prototype={getArgs:function(){return this.args},setArgs:function(r){if("[object Array]"!==Object.prototype.toString.call(r))throw new TypeError("Args must be an Array");this.args=
r},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(r){if(r instanceof k)this.evalOrigin=r;else if(r instanceof Object)this.evalOrigin=new k(r);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var r=this.getFileName()||"",t=this.getLineNumber()||"",G=this.getColumnNumber()||"",L=this.getFunctionName()||"";return this.getIsEval()?r?"[eval] ("+r+":"+t+":"+G+")":"[eval]:"+t+":"+G:L?L+" ("+r+":"+t+":"+G+")":r+":"+t+":"+G}};k.fromString=
function(r){var t=r.indexOf("("),G=r.lastIndexOf(")"),L=r.substring(0,t);t=r.substring(t+1,G).split(",");r=r.substring(G+1);if(0===r.indexOf("@")){var K=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(r,""),V=K[1],H=K[2];K=K[3]}return new k({functionName:L,args:t||void 0,fileName:V,lineNumber:H||void 0,columnNumber:K||void 0})};for(var w=0;w<q.length;w++)k.prototype["get"+f(q[w])]=g(q[w]),k.prototype["set"+f(q[w])]=function(r){return function(t){this[r]=!!t}}(q[w]);for(q=0;q<n.length;q++)k.prototype["get"+f(n[q])]=
g(n[q]),k.prototype["set"+f(n[q])]=function(r){return function(t){if(isNaN(parseFloat(t))||!isFinite(t))throw new TypeError(r+" must be a Number");this[r]=Number(t)}}(n[q]);for(n=0;n<p.length;n++)k.prototype["get"+f(p[n])]=g(p[n]),k.prototype["set"+f(p[n])]=function(r){return function(t){this[r]=String(t)}}(p[n]);return k})})($a);return $a.exports}function La(a){var d=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return d?d[1]:a}function hc(a){var d=document.createElement("a");d.href=a;return{href:d.href,
hostname:d.hostname,pathname:d.pathname}}function ic(a,d){if(-1===a.indexOf("?"+d+"=")&&-1===a.indexOf("&"+d+"="))return a;var f=a.indexOf("?");if(-1===f)return a;var g=a.substr(f+1);f=a.substr(0,f);if(g){var k="",q=g.indexOf("#");-1!==q&&(k=g.substr(q+1),g=g.substr(0,q));q=g.split("&");for(var n=q.length-1;0<=n;n--)g=q[n].split("=")[0],g===d&&q.splice(n,1);(g=q.join("&"))&&(f=f+"?"+g);k&&(f+="#"+k)}return f}function jc(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function tb(a,d){a=a.toLowerCase();
d=d.toLowerCase();if(a===d)return!0;if("."===d.slice(0,1)){if(a===d.slice(1))return!0;var f=a.length-d.length;if(0<f&&a.slice(f)===d)return!0}return!1}function ab(a,d){var f=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(0===a.indexOf("*")&&(a=a.substr(1)),0===a.indexOf(".")&&(a=a.substr(1)),a="http://"+a);f.href=d.toAbsoluteUrl(a);return f.pathname?f.pathname:""}function bb(a,d){return d&&a?0===a.indexOf(d):!1}function ub(a,d){var f=(new RegExp("[\\?&#]"+d+"=([^&#]*)")).exec(a);
return f?decodeURIComponent(f[1]):""}function cb(a,d){a=ic(a,d.visitorIdUrlParameter);return d.discardHashTag?a.replace(/#.*/,""):a}function x(a){return"undefined"!==typeof a}function va(a){return"function"===typeof a}function Ma(a){return"object"===P(a)}function Q(a){return"string"===typeof a||a instanceof String}function pa(a){return"number"===typeof a||Q(a)&&!isNaN(a)&&""!==a}function Na(a){var d=a.length;"."===a.charAt(--d)&&(a=a.slice(0,d));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&
(a=a.substr(0,a.indexOf("/")));return a}function id(a,d,f){a||(a="");d||(d="");if("translate.googleusercontent.com"===a)""===f&&(f=d),d=ub(d,"u"),a=La(d);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))d=document.links[0].href,a=La(d);return[a,d,f]}function Z(a,d){if(a&&a.indexOf)return a.indexOf(d);if(!x(a)||null===a||0===a.length)return-1;for(var f=0;f<a.length;){if(a[f]===d)return f;f++}return-1}function kc(a){if(a)return!x(a.children)&&x(a.childNodes)||
x(a.children)?a.children:[]}function vb(a){var d;for(d=a.parentNode;null!==d&&x(d)&&!u.isLinkElement(a);)a=d,d=a.parentNode;return a}function wb(a){return Math.round((a||new Date).getTime()/1E3)}function wa(a,d){return-1!==a.indexOf(d,a.length-d.length)}function xb(a,d){var f="(^| )(piwik[_-]"+d;if(a)for(var g=0;g<a.length;g++)f+="|"+a[g];return new RegExp(f+")( |$)")}function jd(a,d){var f=u.getAttributeValueFromNode(a,"href");if(!f)return!1;var g=f.split("://");if(2!==g.length)return!1;f=g[0].toLowerCase();
g=g[1];var k=g.indexOf("?");g=-1===k?g:g.slice(0,k);k=[];for(var q=0;q<d.length;q++){var n=d[q];kd.test(n)&&k.push(n)}for(q=0;q<k.length;q++){var p=k[q].split("://");if(2!==p.length)break;n=p[0].toLowerCase();p=p[1];if(f===n&&lc(g,p))return!0}return!1}function lc(a,d){0!==d.lastIndexOf("/",0)&&(d="/"+d);0!==a.lastIndexOf("/",0)&&(a="/"+a);if("/"===d||"/*"===d||a===d)return!0;d=d.toLowerCase();a=a.toLowerCase();if(wa(d,"*"))return(d=d.slice(0,-1))&&"/"!==d&&a!==d?0===a.indexOf(d):!0;wa(a,"/")||(a+=
"/");wa(d,"/")||(d+="/");return 0===a.indexOf(d)}function mc(a,d,f,g){for(var k=0;k<f.length;k++){var q=Na(f[k]),n=ab(f[k],g);if(tb(a,q)&&lc(d,n))return!0}return!1}function nc(a,d,f){a=vb(a);if(u.hasNodeAttribute(a,"href")){var g=u.getAttributeValueFromNode(a,"href");if(g&&!bb(g,f.configTrackerUrl)){var k=hc(g),q=k.pathname||ab(g,d);g=k.hostname||La(k.href);var n=g.toLowerCase();k=k.href.replace(g,n);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(k)&&
(g=a.className,d=mc(n,q,f.configHostsAlias,d),a=u.hasNodeAttribute(a,"download"),bb(k,f.configTrackerUrl)?f=0:(q=xb(f.configDownloadClasses,"download"),n=xb(f.configLinkClasses,"link"),f=new RegExp("\\.("+f.configDownloadExtensions.join("|")+")([?&#]|$)","i"),f=n.test(g)?"link":a||q.test(g)||f.test(k)?"download":d?0:"link"),f))return{type:f,href:k}}}}function R(a,d,f){return 0<=d&&d<=f?"&"+a+"="+d.toString():""}function S(a,d){var f=a[d];return"number"!==typeof f?0:Math.round(f-(a.navigationStart||
0))}function ld(a){var d,f={state:"loading"};if(null!==(d=navigator.userAgentData)&&void 0!==d&&d.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues(md).then(function(g){f={state:"available",hints:g};a.onResolve()})["catch"](function(){f={state:"unavailable"};a.onResolve()});else f={state:"unavailable"};return{getState:function(){return f}}}function oc(a){if(!(a instanceof Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(JSON.stringify(a),
"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var d=0;d<a.length;d++)if("number"!==typeof a[d])return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(JSON.stringify(a),"'")};return{isValid:!0}}function nd(a){var d=!1,f=!1,g=!0,k=pc,q,n=0,p=function(){var r=k[n];q=void 0===r?void 0:window.setTimeout(function(){if(g)a.onPing(qa.PeriodicHeartbeat);n++;p()},1E3*r)},v=function(){f&&
(p(),f=!1);g||(g=!0,a.onPing(qa.PeriodicHeartbeat))},w=function(){g=!1;a.onPing(qa.BlurHeartbeat)};return{enable:function(){d=!0;window.addEventListener("focus",v);window.addEventListener("blur",w);document.hasFocus()?p():f=!0},disable:function(){f=d=!1;clearTimeout(q);q=void 0;n=0;window.removeEventListener("focus",v);window.removeEventListener("blur",w)},setTimings:function(r){var t=oc(r);t.isValid||F(t.error);k=r},isEnabled:function(){return d}}}function od(){var a=[[/g/g,"10"],[/h/g,"11"],[/i/g,
"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]],d=/^[0-9a-f]{16}$/;return function(f){if(f&&!d.test(f)){f=f.toLowerCase().substr(4,16);for(var g=0;g<a.length;g+=1)f=f.replace(a[g][0],a[g][1]);f=f.substr(0,16)}return f}}function pd(a){return{transformIfAMPCookie:od(),getCookieName:function(d){var f=a.getCookiesConfig();
return f.cookieNamePrefix+d+"."+String(f.trackerSiteId)+"."+f.domainHash},getCookie:function(d){return a.getCookiesConfig().cookiesDisabled?0:(d=(new RegExp("(^|;)[ ]*"+d+"=([^;]*)")).exec(a.documentAlias.cookie))?a.decodeWrapper(d[2])||0:0},setCookie:function(d,f,g){var k=a.getCookiesConfig();k.msToExpire=g?g.msToExpire||k.msToExpire:k.msToExpire;k.path=g?g.path||k.path:k.path;k.cookiesDisabled||(f=a.encodeWrapper(f),g=k.msToExpire?new Date(Date.now()+k.msToExpire):void 0,d=d+"="+f+(g?";expires="+
g.toUTCString():"")+";path="+(k.path||"/")+(k.domain?";domain="+k.domain:"")+(k.isSecure?";secure":"")+";SameSite=Lax",document.cookie=d)},deleteCookie:function(d){this.setCookie(d,"",{msToExpire:-86400})},hasCookies:function(){if(a.getCookiesConfig().cookiesDisabled)return"0";if(!x(a.navigatorAlias.cookieEnabled)){var d=this.getCookieName("_pk_testcookie");this.setCookie(d,"1");var f="1"===this.getCookie(d)?"1":"0";this.deleteCookie(d);return f}return a.navigatorAlias.cookieEnabled?"1":"0"}}}function yb(a){function d(g,
k){if(window.getComputedStyle)return document.defaultView.getComputedStyle(g,null)[k];if(g.currentStyle)return g.currentStyle[k]}function f(g,k,q,n,p,v,w){var r=g.parentNode,t;a:{for(t=g.parentNode;t;){if(t===document){t=!0;break a}t=t.parentNode}t=!1}if(!t)return!1;if(9===r.nodeType)return!0;if("0"===d(g,"opacity")||"none"===d(g,"display")||"hidden"===d(g,"visibility"))return!1;x(k)&&x(q)&&x(n)&&x(p)&&x(v)&&x(w)||(k=g.offsetTop,p=g.offsetLeft,n=k+g.offsetHeight,q=p+g.offsetWidth,v=g.offsetWidth,
w=g.offsetHeight);if(a===g&&(0===w||0===v)&&"hidden"===d(g,"overflow"))return!1;if(r){if("hidden"===d(r,"overflow")||"scroll"===d(r,"overflow"))if(p+1>r.offsetWidth+r.scrollLeft||p+v-1<r.scrollLeft||k+1>r.offsetHeight+r.scrollTop||k+w-1<r.scrollTop)return!1;g.offsetParent===r&&(p+=r.offsetLeft,k+=r.offsetTop);return f(r,k,q,n,p,v,w)}return!0}return a?f(a):!1}function qc(a){var d=function(xa,aa){return xa<<aa|xa>>>32-aa},f=function(xa){var aa="",da;for(da=7;0<=da;da--){var zb=xa>>>4*da&15;aa+=zb.toString(16)}return aa},
g,k=[],q=1732584193,n=4023233417,p=2562383102,v=271733878,w=3285377520,r=[];a=unescape(encodeURIComponent(a));var t=a.length;for(g=0;g<t-3;g+=4){var G=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);r.push(G)}switch(t&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(t-1)<<24|8388608;break;case 2:g=a.charCodeAt(t-2)<<24|a.charCodeAt(t-1)<<16|32768;break;case 3:g=a.charCodeAt(t-3)<<24|a.charCodeAt(t-2)<<16|a.charCodeAt(t-1)<<8|128}for(r.push(g);14!==(r.length&15);)r.push(0);
r.push(t>>>29);r.push(t<<3&4294967295);for(a=0;a<r.length;a+=16){for(g=0;16>g;g++)k[g]=r[a+g];for(g=16;79>=g;g++)k[g]=d(k[g-3]^k[g-8]^k[g-14]^k[g-16],1);G=q;t=n;var L=p;var K=v;var V=w;for(g=0;19>=g;g++){var H=d(G,5)+(t&L|~t&K)+V+k[g]+1518500249&4294967295;V=K;K=L;L=d(t,30);t=G;G=H}for(g=20;39>=g;g++)H=d(G,5)+(t^L^K)+V+k[g]+1859775393&4294967295,V=K,K=L,L=d(t,30),t=G,G=H;for(g=40;59>=g;g++)H=d(G,5)+(t&L|t&K|L&K)+V+k[g]+2400959708&4294967295,V=K,K=L,L=d(t,30),t=G,G=H;for(g=60;79>=g;g++)H=d(G,5)+(t^
L^K)+V+k[g]+3395469782&4294967295,V=K,K=L,L=d(t,30),t=G,G=H;q=q+G&4294967295;n=n+t&4294967295;p=p+L&4294967295;v=v+K&4294967295;w=w+V&4294967295}H=f(q)+f(n)+f(p)+f(v)+f(w);return H.toLowerCase()}function ya(a,d){if("undefined"===typeof a)return!0;if("object"!==P(a)||null===a)return F("[".concat(d,"]: parameter 'options' have to be of type object or undefined. Received: ").concat(JSON.stringify(a))),!1;if("string"===typeof a.currencyCode||"undefined"===typeof a.currencyCode)return!0;F("[".concat(d,
"]: parameter 'options.currencyCode' has to be of type string or undefined Received: ").concat(JSON.stringify(a.currencyCode)));return!1}function X(a,d,f,g){if(a.addEventListener)return a.addEventListener(d,f,g),!0;if(a.attachEvent)return a.attachEvent("on"+d,f);a["on"+d]=f}function qd(a){var d={};if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(var f in Ab)if(Object.prototype.hasOwnProperty.call(Ab,f)){var g=navigator.mimeTypes[Ab[f]];d[f]=g&&g.enabledPlugin?
"1":"0"}va(navigator.javaEnabled)&&navigator.javaEnabled()&&(d.java="1");va(window.GearsFactory)&&(d.gears="1");d.cookie=a()}a=parseInt(screen.width,10);f=parseInt(screen.height,10);d.res=a.toString()+"x"+f.toString();return d}function rc(a,d){d||(d=qc);return d((navigator.userAgent||"")+(navigator.platform||"")+JSON.stringify(a)).slice(0,6)}function sc(a){var d=Math.floor((new Date).getTime()/1E3);a=rc(a);return String(d)+a}function rd(a,d,f,g){if(!f.crossDomainTrackingEnabled)return"";g||(g=ub);
a=g(a,f.configVisitorIdUrlParameter);if(!a)return"";a=String(a);g=/^[a-zA-Z0-9]+$/;if(16===a.length&&g.test(a))return a;if(32===a.length&&g.test(a)){a:{g=a.substr(16,32);f=f.configVisitorIdUrlParameterTimeoutInSeconds;d=rc(d);var k=d.length,q=g.substr(-1*k,k);if((g=parseInt(g.substr(0,g.length-k),10))&&q&&q===d){d=Math.floor((new Date).getTime()/1E3);if(0>=f){f=!0;break a}if(d>=g&&d<=g+f){f=!0;break a}}f=!1}if(f)return a.substr(0,16)}return""}function tc(a,d,f){if(a&&u.hasNodeAttribute(a,"href")){var g=
u.getAttributeValueFromNode(a,"href");g&&!bb(g,f.configTrackerUrl)&&(g=(f.crossDomainTrackingLinkDecorator||uc)(g,d+sc(f.browserFeatures),f.configVisitorIdUrlParameter),null!==g&&u.setAnyAttribute(a,"href",g))}}function uc(a,d,f){a=ic(a,f);d||(d="");var g=document.createElement("a");g.href=a;a=g.search.split("&");a.push(encodeURIComponent(f)+"="+encodeURIComponent(d));""===a[0]&&a.shift();g.search=a.join("&");return g.href}function sd(a,d,f){for(var g=[],k=[],q=[],n=0;n<a.length;n++){var p=a[n];p&&
(-1<Z(d,p[0])?g.push(p):-1<Z(f,p[0])?q.push(p):k.push(p))}return{toApplyFirst:g,toApplySecond:k,toApplyLast:q}}function Bb(a){if(!a)return!0;var d,f=!0;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(f=!1);return f}function za(){for(var a=0;a<arguments.length;a+=1){var d=arguments[a];if(!Array.isArray(d)){F("[".concat(I.queueName,".push()]: expected array as argument, got ").concat(JSON.stringify(d),". Example: ").concat(I.queueName,".push(['methodName', parameters]) or ").concat(I.queueName,
".push([function(){}])"));break}for(var f=d.shift(),g=0;g<W.length;g++){var k=W[g];if(va(f))f.apply(k,d);else if(Q(f)){k[f]?k[f].apply(k,d):(k="The method '".concat(f,"' was not found in \"").concat(I.queueName,'" variable.  Please have a look at the Piwik tracker documentation'),F(k));if("addTracker"===f)break;if("setTrackerUrl"===f||"setSiteId"===f)break}}}}function db(a,d,f,g){if(a.removeEventListener)return a.removeEventListener(d,f,g),!0;if(a.detachEvent)return a.detachEvent("on"+d,f);a["on"+
d]===f&&delete a["on"+d]}function Aa(a){"complete"===C.readyState?a():A.addEventListener?A.addEventListener("load",a):A.attachEvent&&A.attachEvent("onload",a)}function Oa(a){var d=!1;(d=C.attachEvent?"complete"===C.readyState:"loading"!==C.readyState)?a():(C.addEventListener?X(C,"DOMContentLoaded",function g(){C.removeEventListener("DOMContentLoaded",g,!1);d||(d=!0,a())}):C.attachEvent&&(C.attachEvent("onreadystatechange",function g(){"complete"===C.readyState&&(C.detachEvent("onreadystatechange",
g),d||(d=!0,a()))}),C.documentElement.doScroll&&A===A.top&&function k(){if(!d){try{C.documentElement.doScroll("left")}catch(q){setTimeout(k,0);return}d=!0;a()}}()),X(A,"load",function(){d||(d=!0,a())},!1))}function td(){var a="";try{var d;a=(null===(d=A.top)||void 0===d?void 0:d.document.referrer)||""}catch(f){if(A.parent)try{a=A.parent.document.referrer}catch(g){a=""}}""===a&&(a=C.referrer);return a}function N(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a}function vc(a,d){return a&&d?a.contains?
a.contains(d):a===d?!0:a.compareDocumentPosition?!!(a.compareDocumentPosition(d)&16):!1:!1}function Cb(a,d){function f(b){if(!1===Db||!0===Eb){var c=new Date;null!==Fb&&18E5<c.getTime()-Fb.getTime()||(c=H("ping=".concat(String(b)),null,"ping"),b=b!==qa.PeriodicHeartbeat,p(c,J,null,b,b?"beacon":void 0))}}function g(b,c){var e=new Image(1,1);e.onload=function(){va(c)&&c()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";e.src=ba+(0>ba.indexOf("?")?"?":"&")+
b}function k(b,c,e){x(e)||(e=!0);try{var h=A.XMLHttpRequest?new A.XMLHttpRequest:A.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;h.open("POST",ba,!0);h.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!e?4===this.readyState&&"function"===typeof c&&c():g(b,c)};h.setRequestHeader("Content-Type",Gb);h.send(b)}catch(l){e&&g(b,c)}}function q(b){b=(new Date).getTime()+b;if(!eb||b>eb)eb=b}function n(b,c){var e=(new Date).getTime();wc=e;Ba&&e<Ba?(e=Ba-e,setTimeout(b,
e),c&&q(e+50),Ba+=50):(void 0===Ba&&(Ba=e+800),b())}function p(b,c,e,h,l){if(Hb){var z=xc.getState();if("loading"===z.state){fb.push({type:"single",request:b,delay:c,callback:e,force:h,method:l});return}"available"===z.state&&(b+=yc(z.hints))}va(Pa)&&(b=Pa(b)||"");if(!gb&&b){b=String(b);var y=l||hb,D=!e&&ra.sendBeacon&&A.Blob&&65536>=b.length,O=!0;l=function(){if("beacon"===y&&D){var ha=new A.Blob([b],{type:Gb});ra.sendBeacon(ba,ha)?O=!1:k(b,e)}else"POST"===y||2E3<b.length?k(b,e):g(b,e);O&&q(c)};
h?l():n(l,O)}}function v(b,c){var e=gb?!1:b?0<b.length:!1;if(e){if(Hb){e=xc.getState();if("loading"===e.state){fb.push({type:"bulk",requests:b,delay:c});return}if("available"===e.state)for(var h=0;h<b.length;h++)b[h]+=yc(e.hints)}if(va(Pa)){e=[];for(h=0;h<b.length;h++){var l=Pa(b[h]);l&&e.push(l)}if(0>=e.length)return;b=e}var z='{"requests":["?'+b.join('","?')+'"]}';n(function(){k(z,null,!1);"beacon"!==hb&&q(c)},!1)}}function w(){zc=Ac((ib||Qa)+(jb||"/")).slice(0,4)}function r(){var b=M.getCookieName("cvar");
b=M.getCookie(b);return Q(b)&&b.length&&(b=JSON.parse(b),Ma(b))?b:{}}function t(){Ca||(Ca=rd(kb,ia,{crossDomainTrackingEnabled:Da,configVisitorIdUrlParameter:"pk_vid",configVisitorIdUrlParameterTimeoutInSeconds:Bc},Cc));var b=wb(new Date),c=M.getCookieName("id");c=M.getCookie(c);return Q(c)&&c.length?(c=c.split("."),c[0]=M.transformIfAMPCookie(c[0]),6>c.length&&(c[1]=b,c[2]=1,c[3]=b,c[4]="",c[5]=""),c.unshift("0"),Ca.length&&(c[1]=Ca),c):c=["1",Ca.length?Ca:"0"===M.hasCookies()?"":Ac((ra.userAgent||
"")+(ra.platform||"")+JSON.stringify(ia)+(new Date).getTime()+Math.random()).slice(0,16),b,1,b,"",""]}function G(){var b=t(),c=b[0],e=b[1],h=b[2],l=b[3],z=b[4],y=b[5];x(b[6])||(b[6]="");return{newVisitor:c,uuid:e,createTs:h,visitCount:l,currentVisitTs:z,lastVisitTs:y,lastEcommerceOrderTs:b[6]}}function L(b){Ea&&(x(b)||(b=G()),b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+b.currentVisitTs+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs,M.setCookie(M.getCookieName("id"),b,{msToExpire:Ib}))}function K(){var b=
sa;sa=!1;var c;for(c=0;c<Jb.length;c++){var e=M.getCookieName(Jb[c]);0!==M.getCookie(e)&&M.deleteCookie(e)}sa=b}function V(b){var c=[];for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&c.push(e);var e={};c.sort();var h=c.length,l;for(l=0;l<h;l++)e[c[l]]=b[c[l]];return e}function H(b,c,e,h){var l=new Date;var z=wb(l);var y=U,D=M.getCookieName("ses"),O=M.getCookieName("cvar"),ha=M.getCookie(D),Sa=Ra||kb;sa&&K();if(gb)return"";D=G();x(h)||(h="");var ta=C.characterSet||C.charset;ta&&"utf-8"!==ta.toLowerCase()||
(ta=void 0);!ha&&z-Number(D.lastVisitTs||D.createTs)>Fa/1E3&&(D.visitCount=Number(D.visitCount)+1,D.lastVisitTs=D.currentVisitTs,D.currentVisitTs=z);0===b.lastIndexOf("action_name=",0)&&(Db=lb,Eb=!!D.uuid,Fb=new Date);b+="&idsite="+Ea+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+l.getHours()+"&m="+l.getMinutes()+"&s="+l.getSeconds()+"&url="+E(cb(Sa,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"}))+(Kb.length?"&urlref="+E(cb(Kb,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"})):"")+(Ua.length?
"&uid="+E(Ua):"")+(lb?"&uia=1":"")+(D.uuid?"&_id="+D.uuid:"")+"&_idts="+D.createTs+"&_idvc="+D.visitCount+(D.lastVisitTs?"&_viewts="+D.lastVisitTs:"")+(String(D.lastEcommerceOrderTs).length?"&_ects="+D.lastEcommerceOrderTs:"")+(ta?"&cs="+E(ta):"")+"&ts_n="+E(mb||Lb)+"&ts_v="+E(Mb||Nb)+(Dc?"":"&rmip=1")+(Ec&&lb?"&dda=1":"");if(!Fc)for(m in ia)Object.prototype.hasOwnProperty.call(ia,m)&&(b+="&"+m+"="+ia[m]);l=[];if(c)for(m in c)Object.prototype.hasOwnProperty.call(c,m)&&/^dimension\d+$/.test(m)&&(z=
m.replace("dimension",""),l.push(parseInt(z,10)),l.push(z),b+="&"+m+"="+c[m],delete c[m]);c&&Bb(c)&&(c=null);for(m in ea)Object.prototype.hasOwnProperty.call(ea,m)&&(z=-1===Z(l,m))&&(z=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==z.exec(ea[m])?b+("&dimension"+m+"="+encodeURIComponent(ea[m])):b+("&dimension"+m+"="+ea[m]));for(m in na)Object.prototype.hasOwnProperty.call(na,m)&&(z=-1===Z(l,m))&&(b+="&dimension"+encodeURIComponent(m)+
"="+encodeURIComponent(na[m]));c?b+="&data="+E(JSON.stringify(c)):oa&&(b+="&data="+E(JSON.stringify(oa)));Bb(ja)||(c=V(ja),b+="&cvar="+E(JSON.stringify(c)));Bb(Va)||(c=V(Va),b+="&e_cvar="+E(JSON.stringify(c)));if(U){b+="&_cvar="+E(JSON.stringify(U));for(m in y)Object.prototype.hasOwnProperty.call(y,m)&&(""===U[m][0]||""===U[m][1])&&delete U[m];Gc&&M.setCookie(O,JSON.stringify(U),{msToExpire:Fa})}var m=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;m=null!==
m&&void 0!==m&&m.timing?m.timing:null!==m&&void 0!==m&&m.getEntriesByType?m.getEntriesByType("navigation")[0]:void 0;y=null;Ob&&(Pb?y=Pb:m&&m.requestStart&&m.responseEnd&&(y=m.responseEnd-m.requestStart),null!==y&&(b+="&gt_ms="+Math.max(y,0)));y=m&&m.loadEventEnd&&0!==m.loadEventEnd&&m.fetchStart&&0!==m.fetchStart;Ob&&("log"===e||"ping"===e)&&2>=nb&&!Hc&&y&&(e="",m.unloadEventStart&&0!==m.unloadEventStart&&(e+=R("t_us",S(m,"unloadEventStart"),65535)),m.unloadEventEnd&&0!==m.unloadEventEnd&&(e+=R("t_ue",
S(m,"unloadEventEnd"),65535)),m.redirectStart&&0!==m.redirectStart&&(e+=R("t_rs",S(m,"redirectStart"),65535)),m.redirectEnd&&0!==m.redirectEnd&&(e+=R("t_re",S(m,"redirectEnd"),65535)),m.secureConnectionStart&&0!==m.secureConnectionStart&&(e+=R("t_ss",S(m,"secureConnectionStart"),65535)),m.fetchStart&&0!==m.fetchStart&&(e+=R("t_fs",S(m,"fetchStart"),65535)),m.domainLookupStart&&0!==m.domainLookupStart&&(e+=R("t_ds",S(m,"domainLookupStart"),65535)),m.connectStart&&0!==m.connectStart&&(e+=R("t_cs",S(m,
"connectStart"),65535)),m.connectEnd&&0!==m.connectEnd&&(e+=R("t_ce",S(m,"connectEnd"),65535)),m.requestStart&&0!==m.requestStart&&(e+=R("t_qs",S(m,"requestStart"),65535)),m.responseStart&&0!==m.responseStart&&(e+=R("t_as",S(m,"responseStart"),65535)),m.responseEnd&&0!==m.responseEnd&&(e+=R("t_ae",S(m,"responseEnd"),65535)),m.domLoading&&0!==m.domLoading&&(e+=R("t_dl",S(m,"domLoading"),65535)),m.domInteractive&&0!==m.domInteractive&&(e+=R("t_di",S(m,"domInteractive"),16777215)),m.domContentLoadedEventStart&&
0!==m.domContentLoadedEventStart&&(e+=R("t_ls",S(m,"domContentLoadedEventStart"),16777215)),m.domContentLoadedEventEnd&&0!==m.domContentLoadedEventEnd&&(e+=R("t_le",S(m,"domContentLoadedEventEnd"),16777215)),m.domComplete&&0!==m.domComplete&&(e+=R("t_dc",S(m,"domComplete"),16777215)),m.loadEventEnd&&0!==m.loadEventEnd&&(e+=R("t_ee",S(m,"loadEventEnd"),16777215)),b+=e,Hc=!0);ob&&(b+="&pv_id="+ob);D.lastEcommerceOrderTs=x(h)&&String(h).length?h:D.lastEcommerceOrderTs;L(D);M.setCookie(M.getCookieName("ses"),
"*",{msToExpire:Fa});Qb.length&&(b+="&"+Qb);return b}function xa(b){if(!Ma(b))return F("Invalid ecommerce product: "+JSON.stringify(b)),!1;if(!Object.prototype.hasOwnProperty.call(b,"sku"))return F("Missing required SKU property in ecommerce product: "+JSON.stringify(b)+"."),!1;var c=P(b.sku);return"string"!==c&&"number"!==c?(F("Product.sku has to be of type string or number. Received: ".concat(c,". In product: ").concat(JSON.stringify(b))),!1):Object.prototype.hasOwnProperty.call(b,"customDimensions")&&
!Ma(b.customDimensions)?(F('Invalid "customDimensions" property. Expected Object type, but got: '+JSON.stringify(b)+"."),!1):!0}function aa(b,c,e,h){var l=new Date,z=[];var y=""+ka("");y+="&e_t="+b;null!==h&&void 0!==h&&h.currencyCode&&(y+="&cur="+h.currencyCode);if(e){b=e.orderId;h=e.grandTotal;var D=e.subTotal;var O=e.tax;var ha=e.shipping;e=e.discount;if(b){y+="&ec_id="+E(b);var Sa=wb(l)}y+="&revenue="+h;pa(D)&&(y+="&ec_st="+D);pa(O)&&(y+="&ec_tx="+O);pa(ha)&&(y+="&ec_sh="+ha);pa(e)&&(y+="&ec_dt="+
e)}for(l=0;l<c.length;l+=1){x(c[l].name)||(c[l].name="");if(!x(c[l].category))c[l].category="";else if(c[l].category instanceof Array)for(e=0;e<c[l].category.length;e+=1)Q(c[l].category[e])||(c[l].category[e]="");x(c[l].price)&&0!==String(c[l].price).length||(c[l].price=0);x(c[l].quantity)&&0!==String(c[l].quantity).length||(c[l].quantity=1);x(c[l].brand)&&0!==String(c[l].brand).length||(c[l].brand="");x(c[l].variant)&&0!==String(c[l].variant).length||(c[l].variant="");x(c[l].customDimensions)||(c[l].customDimensions=
{});e=z;b=e.push;a:for(h=[String(c[l].sku),String(c[l].name),c[l].category,c[l].price,c[l].quantity,c[l].brand,String(c[l].variant),c[l].customDimensions].slice();0<h.length;){D=h[h.length-1];if(!(O=""===D)&&(O=Ma(D)))b:{O=void 0;for(O in D)if(Object.hasOwnProperty.call(D,O)){O=!1;break b}O=!0}if(O)h.pop();else break a}b.call(e,h)}y+="&ec_products="+E(JSON.stringify(z));y=H(y,oa,"ecommerce",Sa);p(y,J)}function da(b){var c,e=!0;if(b instanceof Array){for(c=0;c<b.length;c+=1)e=e&&xa(b[c]);return e}F("Invalid ecommerce products. Expected value: array of objects. Recieved: "+
JSON.stringify(b)+".");return!1}function zb(b,c){var e;if("object"!==P(b)||null===b)return F("Invalid paymentInformation. Expected object. Recieved: "+JSON.stringify(b)+"."),!1;for(e=0;e<c.length;e+=1){var h=c[e];var l=b[h];if("orderId"===h){if(!x(l)||""===String(l))return F('Invalid paymentInformation. Expected object containing "'+h+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!pa(l))return F('Invalid paymentInformation. Expected object containing [number] "'+h+'" attribute. Recieved: '+
JSON.stringify(b)+"."),!1}return!0}function Ic(b,c,e){ya(e,"ecommerceCartUpdate")||(e=void 0);pa(c)?da(b)&&aa("cart-update",b,{grandTotal:c},e):F('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(c)+".")}function Jc(b,c,e){ya(e,"ecommerceOrder")||(e=void 0);da(b)&&zb(c,["orderId","grandTotal"])&&aa("order",b,c,e)}function Kc(){var b,c=[];for(b in Y)if(Object.prototype.hasOwnProperty.call(Y,b)){var e={sku:Y[b][0],name:Y[b][1],category:Y[b][2],price:Y[b][3],quantity:Y[b][4]};
c.push(e)}return c}function ka(b){b=(b=b||pb)&&b.text?b.text:b;if(!Q(b)){var c=document.getElementsByTagName("title");x(c[0])&&(b=c[0].text)}return"action_name="+E(b||"")}function ud(b,c,e){var h="",l;for(l=0;6>l;l++)h+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*Math.random()));ob=h;b=H(ka(b),c,"log");p(b,J,e)}function Wa(b,c,e,h){if(b=B.buildInteractionRequestParams(b,c,e,h))return H("".concat(b,"&").concat(ka()),null,"contentInteraction")}function Rb(b,
c){if(!b||!c)return!1;for(var e=B.findTargetNodes(b),h,l=0;l<e.length;l++)if(h=e[l],vc(h,c)&&B.shouldIgnoreInteraction(h))return!1;e=B.findTargetNodesNoDefault(b);if(!e||0===e.length)return!0;for(l=0;l<e.length;l++)if(h=e[l],vc(h,c))return!0;return!1}function Lc(b,c,e){if(b){var h=B.findParentContentNode(b);if(h&&Rb(h,b)&&(b=B.buildContentBlock(h)))return!b.target&&e&&(b.target=e),B.buildInteractionRequestParams(c,b.name,b.piece,b.target)}}function Mc(b){if(0===ua.length)return!1;var c;for(c=0;c<
ua.length;c++){var e=ua[c];if(e.name===b.name&&e.piece===b.piece&&e.target===b.target)return!0}return!1}function Nc(b){return function(c){if(b){var e=B.findParentContentNode(b);if(Rb(e,c.target||c.srcElement||b)){"beacon"!==hb&&q(J);u.isLinkElement(b)&&u.hasNodeAttributeWithValue(b,"href")&&u.hasNodeAttributeWithValue(b,B.CONTENT_TARGET_ATTR)&&(c=u.getAttributeValueFromNode(b,"href"),bb(c||"",ba)||u.setAnyAttribute(b,B.CONTENT_TARGET_ATTR,""));c=nc(b,B,{configTrackerUrl:ba,configDownloadClasses:Sb,
configLinkClasses:Tb,configDownloadExtensions:la,configHostsAlias:ma});if(Ga&&null!==c&&void 0!==c&&c.type)return c.type;var h=B.buildContentBlock(e);if(h&&(e=h.name,c=h.piece,h=u.getAttributeValueFromNode(b,B.CONTENT_TARGET_ATTR)||h.target,e=Wa("click",e,c,h)))return p("".concat(e,"&").concat(ka()),J),e}}}}function Oc(b){if(null!==b&&void 0!==b&&b.length){var c,e,h;for(c=0;c<b.length;c++){var l=B.findTargetNodes(b[c]);for(h=0;h<l.length;h++)(e=l[h])&&!e.contentInteractionTrackingSetupDone&&(e.contentInteractionTrackingSetupDone=
!0,X(e,"click",Nc(e)))}}}function Pc(b,c){if(null===b||void 0===b||!b.length)return[];var e,h;for(e=0;e<b.length;e++)Mc(b[e])?(b.splice(e,1),e--):ua.push(b[e]);if(!b.length)return[];Oc(c);var l=[];for(e=0;e<b.length;e++)(h=H("".concat(B.buildImpressionRequestParams(b[e].name,b[e].piece,b[e].target),"&").concat(ka()),void 0,"contentImpressions"))&&l.push(h);return l}function Xa(b){var c=B.collectContent(b);return Pc(c,b)}function Ub(b){if(null===b||void 0===b||!b.length)return[];var c;for(c=0;c<b.length;c++)B.isNodeVisible(b[c])||
(b.splice(c,1),c--);return b.length?Xa(b):[]}function Vb(b,c,e){b=B.buildImpressionRequestParams(b,c,e);return H("".concat(b,"&").concat(ka()),null,"contentImpression")}function Qc(b,c){if(b){var e=B.findParentContentNode(b);if(e=B.buildContentBlock(e))return c||(c="Unknown"),Wa(c,e.name,e.piece,e.target)}}function Rc(b,c,e,h,l,z){if(0===N(b).length||0===N(c).length)return F("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),!1;var y=H;b=
"e_c="+E(b)+"&e_a="+E(c)+(x(e)?"&e_n="+E(e):"")+(x(h)?"&e_v="+E(h):"");l=y(b+"&"+ka(""),l,"event");p(l,J,z)}function Sc(b,c,e,h,l){c="".concat(ka(),"&").concat(c,"=").concat(E(cb(b,{discardHashTag:Ta,visitorIdUrlParameter:"pk_vid"})));(b=Lc(l,"click",b))&&(c+="&"+b);e=H(c,e,"link");p(e,J,h,!0,"beacon")}function T(b){!Tc&&"prerendering"in C?C.prerendering?C.addEventListener("prerenderingchange",function e(){C.removeEventListener("prerenderingchange",e);b()}):b():b()}function Wb(b){if(Da){var c=vb(b);
if(jd(c,ma)){tc(c,G().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:ba,browserFeatures:ia,crossDomainTrackingLinkDecorator:Xb});return}}c=nc(b,B,{configTrackerUrl:ba,configDownloadClasses:Sb,configLinkClasses:Tb,configDownloadExtensions:la,configHostsAlias:ma});if(null!==c&&void 0!==c&&c.type)Sc(c.href,c.type,void 0,null,b);else if(Da){b=vb(b);c=B;var e=ma,h=Qa,l=u.getAttributeValueFromNode(b,"href");if(!l||0!==l.indexOf("//")&&0!==l.indexOf("http://")&&0!==l.indexOf("https://"))c=!1;
else{var z=hc(l),y=z.pathname||ab(l,c);l=(z.hostname||La(l)).toLowerCase();c=mc(l,y,e,c)&&!tb(h,Na(l))?!0:!1}c&&tc(b,G().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:ba,browserFeatures:ia,crossDomainTrackingLinkDecorator:Xb})}}function Ya(b){return function(c){c=c||A.event;a:{var e=c;var h=e.which,l=P(e.button);h||"undefined"===l||(C.all&&!C.addEventListener?e.button&1?h=1:e.button&2?h=3:e.button&4&&(h=2):0===e.button||"0"===e.button?h=1:e.button&1?h=2:e.button&2&&(h=3));switch(h){case 1:e=
"left";break a;case 2:e="middle";break a;case 3:e="right";break a}e=void 0}h=c.target||c.srcElement;"click"===c.type?(c=!1,b&&"middle"===e&&(c=!0),h&&!c&&Wb(h)):"mousedown"===c.type?"middle"===e&&h?(qb=e,rb=h):qb=rb=null:"mouseup"===c.type?(e===qb&&h===rb&&Wb(h),qb=rb=null):"contextmenu"===c.type&&Wb(h)}}function vd(b){function c(h){if(h.target){var l=h.target;if(l.closest)l=l.closest("a");else for(;l&&"A"!==l.tagName;)l=l.parentNode;Yb&&l&&!xb(Uc,"ignore").test(l.className)&&Ya(b)(h)}}function e(){db(document.body,
"click",c,!1);b&&(db(document.body,"mouseup",c,!1),db(document.body,"mousedown",c,!1),db(document.body,"contextmenu",c,!1))}Ga||(X(document.body,"click",c,!1),b&&(X(document.body,"mouseup",c,!1),X(document.body,"mousedown",c,!1),X(document.body,"contextmenu",c,!1)),Ga=e)}function Vc(b,c,e){function h(){l=!0}if(Ha)return!0;Ha=!0;var l=!1,z,y;Aa(function(){function D(m){setTimeout(function(){Ha&&(l=!1,e.trackVisibleContentImpressions(),D(m))},m)}function O(m){setTimeout(function(){Ha&&(l&&(l=!1,e.trackVisibleContentImpressions()),
O(m))},m)}function ha(m){if(!m)return!1;var Za=m.getBoundingClientRect();if(0>=Za.width||0>=Za.height)return!1;if(A.getComputedStyle){var ca;var Ia=null===(ca=C.defaultView)||void 0===ca?void 0:ca.getComputedStyle(m,null)}else m.currentStyle&&(Ia=m.currentStyle);Ia||(Ia={});return"0"===Ia.opacity||"none"===Ia.display||"hidden"===Ia.visibility?!1:m.parentNode instanceof Element?ha(m.parentNode):!0}function Sa(m){var Za=[],ca;for(ca=0;ca<m.length;ca+=1)m[ca].isIntersecting&&ha(m[ca].target)&&B.isOrWasNodeInViewport(m[ca].target)&&
Za.push(m[ca].target);m=Xa(Za);v(m,J)}function ta(){if(A.IntersectionObserver){Ja||(Ja=new A.IntersectionObserver(Sa,{threshold:0}));var m=B.findContentNodes();for(y=0;y<m.length;y+=1)m[y].getAttribute(B.CONTENT_WATCHED_ATTR)||(Ja.observe(m[y]),m[y].setAttribute(B.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||c&&0<c)&&ta();if(b){z=["scroll","resize"];for(y=0;y<z.length;y++)C.addEventListener?C.addEventListener(z[y],h):A.attachEvent("on"+z[y],h);O(100)}c&&0<c&&(c=parseInt(c,10),D(c))})}function Wc(b,
c,e,h){if(Zb){var l=String(b).substring(0,16E3);T(function(){var z=c+":"+e;x(h)&&(z+=":"+h);var y=JSON.stringify({category:"JavaScript Errors",action:z,message:l});Xc&&-1!==Z($b,y)||($b.push(y),Rc("JavaScript Errors",z,l))})}}var ac=id(C.domain,A.location.href,td()),Qa=Na(ac[0]),kb=ac[1],Kb=ac[2],Zb=!1,hb="beacon",Dc=!0,Ec=!1,Hb=!1,Gb="application/x-www-form-urlencoded; charset=UTF-8",ba=a||"",bc="",Qb="",Ea=d||"",lb=!1,Fc=!1,Db=null,Eb=null,Ua="",Ca="",cc=10,Ra,pb="",la="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
ma=[Qa],Uc=[],Sb=[],Tb=[],J=500,Fb=null,Yc=!1,Ta=!1,oa,Zc="_pk_",Bc=180,ib,jb,$c=!1,sa=!1,ad=!0,gb=!1,Tc=!1,Ib=339552E5,Fa=18E5,Ob=!0,Pb=0,Gc=!1,U,ja={},Va={},Pa,ea={},na={},dc=200,Y={},ia={},ua=[],Ha=!1,Ja,Ba,Ga=!1,Yb=!1,Da=!1,Xb=uc,Cc=ub,wc=null,qb,rb,Ac=qc,zc,ob,nb=0,Xc=!1,$b=[],Jb=["id","ses","cvar"],Lb="jstc",Nb="2.30.0",mb="",Mb="",xc=ld({onResolve:function(){for(var b=0;b<fb.length;b++){var c=fb[b];if("single"===c.type)p(c.request,c.delay,c.callback,c.force,c.method);else if("bulk"===c.type)v(c.requests,
c.delay);else throw Error("[processQueue] unprocessable request type: ".concat(JSON.stringify(c)));}}});try{pb=C.title}catch(b){pb=""}var Ka=nd({onPing:f}),M=pd({decodeWrapper:wd,encodeWrapper:E,getCookiesConfig:function(){return{cookiesDisabled:sa,domain:ib,path:jb,isSecure:$c,trackerSiteId:Ea,cookieNamePrefix:Zc,domainHash:zc}},documentAlias:C,navigatorAlias:ra}),fb=[];this.setCustomVariableMaximumLength=function(b){dc=b};ia=qd(function(){return M.hasCookies()});w();this.getQuery=function(){return u};
this.getContent=function(){return B};this.buildContentImpressionRequest=Vb;this.buildContentInteractionRequest=Wa;this.buildContentInteractionRequestNode=Qc;this.getContentImpressionsRequestsFromNodes=Xa;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=Ub;this.trackCallbackOnLoad=Aa;this.trackCallbackOnReady=Oa;this.buildContentImpressionsRequests=Pc;this.wasContentImpressionAlreadyTracked=Mc;this.appendContentInteractionToRequestIfPossible=Lc;this.setupInteractionsTracking=Oc;this.trackContentImpressionClickInteraction=
Nc;this.internalIsNodeVisible=yb;this.isNodeAuthorizedToTriggerInteraction=Rb;this.getDomains=function(){return ma};this.getConfigIdPageView=function(){return ob};this.getConfigDownloadExtensions=function(){return la};this.enableTrackOnlyVisibleContent=function(b,c){return Vc(b,c,this)};this.clearTrackedContentImpressions=function(){ua=[]};this.getTrackedContentImpressions=function(){return ua};this.clearEnableTrackOnlyVisibleContent=function(){var b;Ha=!1;null===(b=Ja)||void 0===b||b.disconnect();
Ja=void 0};this.disableLinkTracking=function(){"function"===typeof Ga&&Ga();Yb=Ga=!1};this.getConfigVisitorCookieTimeout=function(){return Ib};this.removeAllAsyncTrackersButFirst=function(){W=[W[0]]};this.ping=function(){var b=H("ping=6",null,"ping");p(b,J)};this.getVisitorId=function(){return G().uuid};this.getVisitorInfo=function(){return t()};this.setTrackerUrl=function(b){ba=b};this.getTrackerUrl=function(){return ba};this.getPiwikUrl=function(){var b=this.getTrackerUrl();if(bc)b=bc;else{b=B.toAbsoluteUrl(b);
if(-1!==b.indexOf("?")){var c=b.indexOf("?");b=b.slice(0,c)}wa(b,"ppms.php")?b=b.substr(0,b.length-8):wa(b,".php")&&(c=b.lastIndexOf("/"),b=b.slice(0,c+1));wa(b,"/js/")&&(b=b.substr(0,b.length-3))}return b};this.addTracker=function(b,c){if(!c)throw Error("A siteId must be given to add a new tracker");x(b)&&null!==b||(b=this.getTrackerUrl());var e=new Cb(b,c);W.push(e);return e};this.getSiteId=function(){return Ea};this.setSiteId=function(b){Ea=b;L();if(ad){var c=this.getTrackerUrl(),e=C.createElement("script");
e.setAttribute("id","ppas_container_configuration");e.setAttribute("data-appid",b);b=e.setAttribute;var h=C.createElement("a");h.href=c;b.call(e,"data-host",h.host);C.getElementsByTagName("head")[0].appendChild(e)}};this.setVisitorIdCookie=function(){L()};this.resetUserId=function(){Ua=""};this.setUserIsAnonymous=function(b){lb=b};this.setSessionIdStrictPrivacyMode=function(b){Fc=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);
cc=b};this.getTimingDataSamplingOnPageLoad=function(){return cc};this.setUserId=function(b){x(b)&&b.length&&(Ua=b)};this.getUserId=function(){return Ua};this.setCustomData=function(b,c){Ma(b)?oa=b:(oa||(oa={}),oa[b]=c)};this.getCustomData=function(){return oa};this.setCustomRequestProcessing=function(b){Pa=b};this.appendToTrackingUrl=function(b){Qb=b};this.getRequest=function(b){return H(b)};this.setCustomDimension=function(b,c){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(na,b)?fd("Custom dimension "+
b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):(x(c)||(c=""),Q(c)||(c=String(c)),ea[b]=c))};this.getCustomDimension=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(ea,b))return ea[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete ea[b],delete na[b])};this.setCustomDimensionValue=function(b,c){b=parseInt(b,10);0<b&&(x(c)||(c=""),Q(c)||(c=String(c)),na[b]=c,delete ea[b])};this.getCustomDimensionValue=
function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(na,b))return na[b]};this.setCustomVariable=function(b,c,e,h){x(h)||(h="visit");x(c)&&(x(e)||(e=""),0<b&&(c=Q(c)?c:String(c),e=Q(e)?e:String(e),c=[c.slice(0,dc),e.slice(0,dc)],"visit"===h||2===h?(U||(U=r()),U[b]=c):"page"===h||3===h?ja[b]=c:"event"===h&&(Va[b]=c)))};this.getCustomVariable=function(b,c){x(c)||(c="visit");if("page"===c||3===c)var e=ja[b];else if("event"===c)e=Va[b];else if("visit"===c||2===c)U||(U=r()),e=U[b];
return x(e)&&""!==e[0]?e:!1};this.deleteCustomVariable=function(b,c){this.getCustomVariable(b,c)&&this.setCustomVariable(b,"","",c)};this.deleteCustomVariables=function(b){if("page"===b||3===b)ja={};else if("event"===b)Va={};else if("visit"===b||2===b)U={}};this.storeCustomVariablesInCookie=function(){Gc=!0};this.setLinkTrackingTimer=function(b){J=b};this.getLinkTrackingTimer=function(){return J};this.setDownloadExtensions=function(b){Q(b)&&(b=b.split("|"));la=b};this.addDownloadExtensions=function(b){var c;
Q(b)&&(b=b.split("|"));for(c=0;c<b.length;c++)la.push(b[c])};this.removeDownloadExtensions=function(b){var c,e=[];Q(b)&&(b=b.split("|"));for(c=0;c<la.length;c++)-1===Z(b,la[c])&&e.push(la[c]);la=e};this.setDomains=function(b){ma=Q(b)?[b]:b;b=!1;for(var c=0;c<ma.length;c++){var e=String(ma[c]);if(tb(Qa,Na(e))){b=!0;break}if((e=ab(e,B))&&"/"!==e&&"/*"!==e){b=!0;break}}b||ma.push(Qa)};this.enableCrossDomainLinking=function(){Da=!0};this.disableCrossDomainLinking=function(){Da=!1};this.isCrossDomainLinkingEnabled=
function(){return Da};this.customCrossDomainLinkDecorator=function(b){Xb=b};this.customCrossDomainLinkVisitorIdGetter=function(b){Cc=b};this.setCrossDomainLinkingTimeout=function(b){Bc=b};this.getCrossDomainLinkingUrlParameter=function(){var b=G().uuid;return E("pk_vid")+"="+E(b+sc(ia))};this.setIgnoreClasses=function(b){Uc=Q(b)?[b]:b};this.setRequestMethod=function(b){hb=b||"beacon"};this.setRequestContentType=function(b){Gb=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=
function(b){Kb=b};this.setCustomUrl=function(b){if("string"!==typeof b)F("[setCustomUrl]: url must be a string, got: ".concat(JSON.stringify(b)));else{var c=kb,e=Ta;jc(b)?Ra=b:"/"===b.slice(0,1)?Ra=(jc(c)||"")+"://"+La(c)+b:(c=cb(c,{discardHashTag:e,visitorIdUrlParameter:"pk_vid"}),e=c.indexOf("?"),0<=e&&(c=c.slice(0,e)),e=c.lastIndexOf("/"),e!==c.length-1&&(c=c.slice(0,e+1)),Ra=c+b)}};this.getCurrentUrl=function(){return Ra||kb};this.setDocumentTitle=function(b){pb=b};this.setAPIUrl=function(b){bc=
b};this.setDownloadClasses=function(b){Sb=Q(b)?[b]:b};this.setLinkClasses=function(b){Tb=Q(b)?[b]:b};this.discardHashTag=function(b){Ta=b};this.setCookieNamePrefix=function(b){Zc=b;U=r()};this.setCookieDomain=function(b){ib=Na(b);w()};this.getCookieDomain=function(){return ib};this.hasCookies=function(){return"1"===M.hasCookies()};this.setSessionCookie=function(b,c,e){if(!b)throw Error("Missing cookie name");x(e)||(e=Fa);Jb.push(b);M.setCookie(M.getCookieName(b),c,{msToExpire:e})};this.getCookie=
function(b){b=M.getCookie(M.getCookieName(b));return 0===b?null:b};this.setCookiePath=function(b){jb=b;w()};this.getCookiePath=function(){return jb};this.setVisitorCookieTimeout=function(b){Ib=1E3*b};this.setSessionCookieTimeout=function(b){Fa=1E3*b};this.getSessionCookieTimeout=function(){return Fa};this.setReferralCookieTimeout=function(){};this.setSecureCookie=function(b){$c=b};this.disableCookies=function(){sa=!0;Ea&&K()};this.enableCookies=function(){sa=!1};this.deleteCookies=function(){K()};
this.setSiteInspectorSetup=function(b){ad=b};this.setDoNotTrack=function(b){var c=ra.doNotTrack||ra.msDoNotTrack;(gb=b&&("yes"===c||"1"===c))&&this.disableCookies()};this.addListener=function(b,c){var e=c;"undefined"===P(e)&&(e=!0);X(b,"click",Ya(!!e),!1);e&&(X(b,"mouseup",Ya(e),!1),X(b,"mousedown",Ya(e),!1),X(b,"contextmenu",Ya(e),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);Yb=!0;T(function(){Oa(function(){vd(b)})})};this.enableJSErrorTracking=
function(b){x(b)||(b=!0);if(!Zb){Zb=!0;Xc=b;var c=A.onerror;A.onerror=function(e,h,l,z,y){Wc(e,h,l,z);return c?c(e,h,l,z,y):!1}}};this.disablePerformanceTracking=function(){Ob=!1};this.setGenerationTimeMs=function(b){Pb=parseInt(b,10)};this.enableHeartBeatTimer=function(b){if(b){var c=oc(b);if(!c.isValid){F(c.error);return}}else b=pc;Ka.setTimings(b);Yc=!0;null!==wc&&Ka.enable()};this.disableHeartBeatTimer=function(){Ka.disable()};this.killFrame=function(){A.location!==A.top.location&&(A.top.location=
A.location)};this.redirectFile=function(b){"file:"===A.location.protocol&&(A.location=b)};this.setCountPreRendered=function(b){Tc=b};this.trackGoal=function(b,c,e,h){ya(h,"trackGoal")||(h=void 0);T(function(){var l=h;l=H("idgoal="+b+(c?"&revenue="+c:"")+"&"+ka("")+(null!==l&&void 0!==l&&l.currencyCode?"&cur="+l.currencyCode:""),e,"goal");p(l,J)})};this.trackLink=function(b,c,e,h){T(function(){Sc(b,c,e,h)})};this.getNumTrackedPageViews=function(){return nb};this.trackHeartBeat=function(b){var c=!C.hasFocus||
C.hasFocus();Ka.isEnabled()&&c&&(!1===Db||!0===Eb)&&(c=qa.PeriodicHeartbeat,null!==b&&void 0!==b&&b.lastHeartbeat&&(c=qa.LastHeartbeat),null!==b&&void 0!==b&&b.blurHeartbeat&&(c=qa.BlurHeartbeat),f(c))};this.trackPageView=function(b,c,e){ua=[];$b=[];T(function(){nb++;ud(b,c,e);Yc&&!Ka.isEnabled()&&Ka.enable();1>=nb&&cc>=Math.floor(100*Math.random()+1)&&Aa(function(){setTimeout(function(){var h=H("ping=5",null,"ping");p(h,J)},0)})})};this.trackAllContentImpressions=function(){T(function(){Oa(function(){var b=
B.findContentNodes();b=Xa(b);v(b,J)})})};this.trackVisibleContentImpressions=function(b,c){x(b)||(b=!0);x(c)||(c=750);Vc(b,c,this);Ja||T(function(){Aa(function(){var e=B.findContentNodes();e=Ub(e);v(e,J)})})};this.trackContentImpression=function(b,c,e){b=N(b);c=N(c||"Unknown");e=N(e||"");b&&T(function(){var h=Vb(b,c,e);p(h,J)})};this.trackPersonalizationContentImpression=function(b,c,e,h){b=N(b);c=N(c);e=N(e||"Unknown");h=N(h||"");b?c?T(function(){var l=Vb(c,e,h);l+="&c_persid="+E(b);p(l,J)}):F("[trackPersonalizationContentImpression]: contentName is required."):
F("[trackPersonalizationContentImpression]: personalizationId is required.")};this.trackContentImpressionsWithinNode=function(b){b&&T(function(){Ha?Aa(function(){var c=B.findContentNodesWithinNode(b);c=Ub(c);v(c,J)}):Oa(function(){var c=B.findContentNodesWithinNode(b);c=Xa(c);v(c,J)})})};this.trackContentInteraction=function(b,c,e,h){b=N(b);c=N(c);e=N(e||"Unknown");h=N(h||"");b&&c&&T(function(){var l=Wa(b,c,e,h);l&&p(l,J)})};this.trackPersonalizationContentInteraction=function(b,c,e,h,l){b=N(b);c=
N(c);e=N(e);h=N(h||"Unknown");l=N(l||"");b?c?e?T(function(){var z=Wa(c,e,h,l);z&&(z+="&c_persid="+E(b),p(z,J))}):F("[trackPersonalizationContentInteraction]: contentName is required."):F("[trackPersonalizationContentInteraction]: contentInteraction is required."):F("[trackPersonalizationContentInteraction]: personalizationId is required.")};this.trackContentInteractionNode=function(b,c){b&&T(function(){var e=Qc(b,c);e&&p(e,J)})};this.logAllContentBlocksOnPage=function(){var b=B.findContentNodes();
b=B.collectContent(b);console.log(b)};this.trackEvent=function(b,c,e,h,l,z){x(h)&&!pa(h)&&F("[trackEvent]: Value parameter must be a number or number representation. Received: ".concat(JSON.stringify(h)));T(function(){Rc(String(b),String(c),e,h,l,z)})};this.trackSiteSearch=function(b,c,e,h){T(function(){var l=H("search="+E(b)+(c?"&search_cats="+E(JSON.stringify(Q(c)?[c]:c)):"")+(x(e)?"&search_count="+e:""),h,"sitesearch");p(l,J)})};this.setEcommerceView=function(b,c,e,h){x(e)&&e.length?e instanceof
Array&&(e=JSON.stringify(e)):e="";ja[5]=["_pkc",e];x(h)&&String(h).length&&(ja[2]=["_pkp",h]);if(x(b)&&b.length||x(c)&&c.length)x(b)&&b.length&&(ja[3]=["_pks",b]),x(c)&&c.length||(c=""),ja[4]=["_pkn",c]};this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(Y))};this.addEcommerceItem=function(b,c,e,h,l){b.length&&(Y[b]=[b,c,e,h,l])};this.removeEcommerceItem=function(b){b.length&&delete Y[b]};this.clearEcommerceCart=function(){Y={}};this.trackEcommerceOrder=function(b,c,e,h,l,z){String(b).length&&
x(c)&&(Jc(Kc(),{orderId:b,grandTotal:c,subTotal:e,tax:h,shipping:l,discount:z}),Y={})};this.trackEcommerceCartUpdate=function(b){Ic(Kc(),b)};this.ecommerceProductDetailView=function(b,c){ya(c,"ecommerceProductDetailView")||(c=void 0);da(b)&&aa("product-detail-view",b,void 0,c)};this.ecommerceAddToCart=function(b,c){ya(c,"ecommerceAddToCart")||(c=void 0);da(b)&&aa("add-to-cart",b,void 0,c)};this.ecommerceRemoveFromCart=function(b,c){ya(c,"ecommerceRemoveFromCart")||(c=void 0);da(b)&&aa("remove-from-cart",
b,void 0,c)};this.ecommerceCartUpdate=Ic;this.ecommerceOrder=Jc;this.trackError=function(b){if(b)try{var c=xd.parse(b)[0];Wc(b.message,c.fileName||"",c.lineNumber||0,c.columnNumber||0)}catch(e){}};this.trackRequest=function(b,c,e,h){T(function(){var l=H(b,c,h);p(l,J,e)})};this.deanonymizeUser=function(){this.setUserIsAnonymous(!1);var b=H("ping=4",null,"ping");p(b,J)};this.getTrackingSource=function(){return[Lb,Nb]};this.setTrackingSource=function(b,c){Lb=String(b);void 0!==c&&(Nb=String(c))};this.setTrackingSourceProvider=
function(b,c){"string"!==typeof b?F("[setTrackingSourceProvider]: 'provider' has to be of type string"):"string"!==typeof c?F("[setTrackingSourceProvider]: 'providerVersion' has to be of type string"):(mb=b,Mb=c)};this.getTrackingSourceProvider=function(){if(mb)return[mb,Mb]};this.setIpTracking=function(b){Dc=b};this.setDeviceDataAnonymization=function(b){"boolean"!==typeof b?F("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):Ec=b};this.setEnableClientHints=
function(b){"boolean"!==typeof b?F("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Hb=b};ec.trigger("TrackerSetup",[this])}function yd(a,d){for(var f={},g=0;g<d.length;g++){var k=d[g];f[k]=1;for(var q=0;q<a.length;q++){var n;if(null!==(n=a[q])&&void 0!==n&&n[0]){var p=a[q][0];k===p&&(za(a[q]),delete a[q],1<f[p]&&"addTracker"!==p&&"enableLinkTracking"!==p&&"setSecureCookie"!==p&&"enableCrossDomainLinking"!==p&&F("The method "+p+' is registered more than once in "'+
I.queueName+'" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),f[p]++)}}}za(["setVisitorIdCookie"])}function bd(a,d){var f=new Cb(a,d);W.push(f);var g=window[I.queueName].splice(0,window[I.queueName].length),k=sd(g,cd,zd),q=k.toApplySecond;g=k.toApplyLast;yd(k.toApplyFirst,cd);for(k=0;k<q.length;k++)za(q[k]);q=window[I.queueName];for(k=0;k<q.length;k++)za(q[k]);for(q=0;q<g.length;q++)za(g[q]);if("number"===typeof window[I.queueName].length){var n=
{push:za},p=Date.now();window[I.queueName]=n;var v=setInterval(function(){6E4<Date.now()-p?clearInterval(v):window[I.queueName]!==n&&(F("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),clearInterval(v))},1E3)}else F("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");
return f}function Ad(a,d,f,g){function k(n){try{if(window["piwik_"+n])return window["piwik_"+n]}catch(p){}}var q=window.Piwik.getTracker(f,d);q.setDocumentTitle(a);q.setCustomData(g);(a=k("tracker_pause"))&&q.setLinkTrackingTimer(a);(a=k("download_extensions"))&&q.setDownloadExtensions(a);(a=k("hosts_alias"))&&q.setDomains(a);(a=k("ignore_classes"))&&q.setIgnoreClasses(a);q.setTimingDataSamplingOnPageLoad(0);q.trackPageView();k("install_tracker")&&(window.piwik_track=function(n,p,v,w){q.setSiteId(p);
q.setTrackerUrl(v);q.trackLink(n,w)},q.enableLinkTracking())}var I={queueName:"_paq",objectName:"Piwik"},sb={exports:{}},$a={exports:{}},hd=$a.exports,gc,Bd=sb.exports,dd,xd=function(a){return a&&a.__esModule&&Object.prototype.hasOwnProperty.call(a,"default")?a["default"]:a}(function(){if(dd)return sb.exports;dd=1;(function(a,d){(function(f,g){a.exports=g(gd())})(Bd,function(f){var g=/(^|@)\S+:\d+/,k=/^\s*at .*(\S+:\d+|\(native\))/m,q=/^(eval@)?(\[native code])?$/;return{parse:function(n){if("undefined"!==
typeof n.stacktrace||"undefined"!==typeof n["opera#sourceloc"])return this.parseOpera(n);if(n.stack&&n.stack.match(k))return this.parseV8OrIE(n);if(n.stack)return this.parseFFOrSafari(n);throw Error("Cannot parse given Error object");},extractLocation:function(n){if(-1===n.indexOf(":"))return[n];n=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(n.replace(/[()]/g,""));return[n[1],n[2]||void 0,n[3]||void 0]},parseV8OrIE:function(n){return n.stack.split("\n").filter(function(p){return!!p.match(k)},this).map(function(p){-1<
p.indexOf("(eval ")&&(p=p.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,""));var v=p.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),w=v.match(/ (\(.+\)$)/);v=w?v.replace(w[0],""):v;var r=this.extractLocation(w?w[1]:v);v=w&&v||void 0;w=-1<["eval","<anonymous>"].indexOf(r[0])?void 0:r[0];return new f({functionName:v,fileName:w,lineNumber:r[1],columnNumber:r[2],source:p})},this)},parseFFOrSafari:function(n){return n.stack.split("\n").filter(function(p){return!p.match(q)},
this).map(function(p){-1<p.indexOf(" > eval")&&(p=p.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,":$1"));if(-1===p.indexOf("@")&&-1===p.indexOf(":"))return new f({functionName:p});var v=/((.*".+"[^@]*)?[^@]*)(?:@)/,w=p.match(v);w=w&&w[1]?w[1]:void 0;v=this.extractLocation(p.replace(v,""));return new f({functionName:w,fileName:v[0],lineNumber:v[1],columnNumber:v[2],source:p})},this)},parseOpera:function(n){return!n.stacktrace||-1<n.message.indexOf("\n")&&n.message.split("\n").length>
n.stacktrace.split("\n").length?this.parseOpera9(n):n.stack?this.parseOpera11(n):this.parseOpera10(n)},parseOpera9:function(n){var p=/Line (\d+).*script (?:in )?(\S+)/i;n=n.message.split("\n");for(var v=[],w=2,r=n.length;w<r;w+=2){var t=p.exec(n[w]);t&&v.push(new f({fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera10:function(n){var p=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;n=n.stacktrace.split("\n");for(var v=[],w=0,r=n.length;w<r;w+=2){var t=p.exec(n[w]);t&&
v.push(new f({functionName:t[3]||void 0,fileName:t[2],lineNumber:t[1],source:n[w]}))}return v},parseOpera11:function(n){return n.stack.split("\n").filter(function(p){return!!p.match(g)&&!p.match(/^Error created at/)},this).map(function(p){var v=p.split("@"),w=this.extractLocation(v.pop()),r=v.shift()||"";v=r.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var t;r.match(/\(([^)]*)\)/)&&(t=r.replace(/^[^(]+\(([^)]*)\)$/,"$1"));t=void 0===t||"[arguments not available]"===
t?void 0:t.split(",");return new f({functionName:v,args:t,fileName:w[0],lineNumber:w[1],columnNumber:w[2],source:p})},this)}}})})(sb);return sb.exports}()),u={htmlCollectionToArray:function(a){var d=[],f;if(!a||!a.length)return d;for(f=0;f<a.length;f++)d.push(a[f]);return d},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return u.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var d,f=[];for(d=0;d<a.length;d++){var g=u.find(a[d]);
f=f.concat(g)}return f=u.makeNodesUnique(f)},findNodesByTagName:function(a,d){if(!a||!d||!a.getElementsByTagName)return[];var f=a.getElementsByTagName(d);return u.htmlCollectionToArray(f)},makeNodesUnique:function(a){var d=[].concat(a);a.sort(function(n,p){if(n===p)return 0;var v=Z(d,n),w=Z(d,p);return v===w?0:v>w?-1:1});if(1>=a.length)return a;var f=0,g=0,k=[],q;for(q=a[f++];q;)q===a[f]&&(g=k.push(f)),q=a[f++]||null;for(;g--;)a.splice(k[g],1);return a},getAttributeValueFromNode:function(a,d){if(u.hasNodeAttribute(a,
d)){if(a&&a.getAttribute)return a.getAttribute(d);if(a&&a.attributes&&"undefined"!==P(a.attributes[d])){if(a.attributes[d].value)return a.attributes[d].value;if(a.attributes[d].nodeValue)return a.attributes[d].nodeValue;var f,g=a.attributes;if(g){for(f=0;f<g.length;f++)if(g[f].nodeName===d)return g[f].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,d){return!!u.getAttributeValueFromNode(a,d)},hasNodeAttribute:function(a,d){return a&&a.hasAttribute?a.hasAttribute(d):a&&a.attributes?
"undefined"!==P(a.attributes[d]):!1},hasNodeCssClass:function(a,d){if(a&&d&&a.className){var f="string"===typeof a.className?a.className.split(" "):[];if(-1!==Z(f,d))return!0}return!1},findNodesHavingAttribute:function(a,d,f){f||(f=[]);if(!a||!d)return f;a=kc(a);if(!a)return f;var g;for(g=0;g<a.length;g++){var k=a[g];u.hasNodeAttribute(k,d)&&f.push(k);f=u.findNodesHavingAttribute(k,d,f)}return f},findFirstNodeHavingAttribute:function(a,d){if(a&&d){if(u.hasNodeAttribute(a,d))return a;var f=u.findNodesHavingAttribute(a,
d);if(f&&f.length)return f[0]}},findFirstNodeHavingAttributeWithValue:function(a,d){if(a&&d){if(u.hasNodeAttributeWithValue(a,d))return a;var f=u.findNodesHavingAttribute(a,d);if(f&&f.length){var g;for(g=0;g<f.length;g++)if(u.getAttributeValueFromNode(f[g],d))return f[g]}}},findNodesHavingCssClass:function(a,d,f){f||(f=[]);if(!a||!d)return f;if(a.getElementsByClassName)return d=a.getElementsByClassName(d),u.htmlCollectionToArray(d);a=kc(a);if(!a)return[];var g;for(g=0;g<a.length;g++){var k=a[g];u.hasNodeCssClass(k,
d)&&f.push(k);f=u.findNodesHavingCssClass(k,d,f)}return f},findFirstNodeHavingClass:function(a,d){if(a&&d){if(u.hasNodeCssClass(a,d))return a;var f=u.findNodesHavingCssClass(a,d);if(f&&f.length)return f[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==Z(["a","area"],a)},setAnyAttribute:function(a,d,f){a&&d&&(a.setAttribute?a.setAttribute(d,f):a[d]=f)}},kd=/^[a-z]+:\/\/.+$/i,ed={model:"ch_m",brands:"ch_b",platform:"ch_p",platformVersion:"ch_pv",fullVersionList:"ch_fvl"},
md=Object.keys(ed),yc=function(a){if("object"!==P(a))return"";var d="",f;for(f in a){var g=ed[f],k=a[f];if(g&&k){g="&".concat(g,"=");var q=g.concat;k?(k="object"===P(k)?JSON.stringify(k):k,k=window.encodeURIComponent(k)):k="";d+=q.call(g,k)}}return d},pc=[15,30,60,120,240,480,960,1800],qa={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3},Ab=Object.freeze({pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"}),eb,fa={},C=document,ra=navigator,A=window,Hc=!1,E=A.encodeURIComponent,wd=A.decodeURIComponent,W=[],fc=[],B={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",
CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,findContentNodes:function(){return u.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var d=u.findNodesHavingCssClass(a,this.CONTENT_CLASS),f=u.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(f.length){var g;for(g=0;g<f.length;g++)d.push(f[g])}u.hasNodeAttribute(a,this.CONTENT_ATTR)?d.push(a):u.hasNodeCssClass(a,
this.CONTENT_CLASS)&&d.push(a);return d=u.makeNodesUnique(d)},findParentContentNode:function(a){if(a)for(var d=0;a&&a!==C&&a.parentNode;){if(u.hasNodeAttribute(a,this.CONTENT_ATTR)||u.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<d)break;d++}},findPieceNode:function(a){var d;(d=u.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(d=u.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return d?d:a},findTargetNodeNoDefault:function(a){if(a){var d=u.findFirstNodeHavingAttributeWithValue(a,
this.CONTENT_TARGET_ATTR);if(d||(d=u.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(d=u.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return d}},findTargetNode:function(a){var d=this.findTargetNodeNoDefault(a);return d?d:a},findTargetNodesNoDefault:function(a){if(a){var d=u.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(0<d.length)return d;d=u.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS);if(0<d.length)return d}},findTargetNodes:function(a){var d=B.findTargetNodesNoDefault(a);
return d&&0<d.length?d:[a]},findContentName:function(a){if(a){var d=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(d)return u.getAttributeValueFromNode(d,this.CONTENT_NAME_ATTR);if(d=this.findContentPiece(a))return this.removeDomainIfIsInLink(d);if(u.hasNodeAttributeWithValue(a,"title"))return u.getAttributeValueFromNode(a,"title");d=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(d,"title"))return u.getAttributeValueFromNode(d,"title");a=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(a,
"title"))return u.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var d=u.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(d)return u.getAttributeValueFromNode(d,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var d=this.findTargetNode(a);if(u.hasNodeAttributeWithValue(d,this.CONTENT_TARGET_ATTR))return u.getAttributeValueFromNode(d,this.CONTENT_TARGET_ATTR);
if(u.hasNodeAttributeWithValue(d,"href"))return a=u.getAttributeValueFromNode(d,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(u.hasNodeAttributeWithValue(a,"href"))return a=u.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){var d;null!==(d=a)&&void 0!==d&&d.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&
this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var d=a.nodeName.toLowerCase(),f=u.findFirstNodeHavingAttributeWithValue(a,"src");if(-1!==Z(["img","embed","video","audio"],d)&&f)return u.getAttributeValueFromNode(f,"src");if("object"===d&&u.hasNodeAttributeWithValue(a,"data"))return u.getAttributeValueFromNode(a,"data");if("object"===d){d=u.findNodesByTagName(a,"param");if(d.length)for(f=0;f<d.length;f++)if("movie"===u.getAttributeValueFromNode(d[f],
"name")&&u.hasNodeAttributeWithValue(d[f],"value"))return u.getAttributeValueFromNode(d[f],"value");a=u.findNodesByTagName(a,"embed");if(a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return N(a)},isOrWasNodeInViewport:function(a){if(null===a||void 0===a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var d=a.getBoundingClientRect(),f=C.documentElement,g=0>d.top;g&&a.offsetTop&&(g=0<a.offsetTop+d.height);a=f.clientWidth;A.innerWidth&&a>A.innerWidth&&(a=A.innerWidth);f=f.clientHeight;
A.innerHeight&&f>A.innerHeight&&(f=A.innerHeight);return(0<d.bottom||g)&&0<d.right&&d.left<a&&(d.top<f||g)},isNodeVisible:function(a){var d=yb(a);a=this.isOrWasNodeInViewport(a);return d&&a},buildInteractionRequestParams:function(a,d,f,g){var k="";a&&(k+="c_i="+E(a));d&&(k&&(k+="&"),k+="c_n="+E(d));f&&(k&&(k+="&"),k+="c_p="+E(f));g&&(k&&(k+="&"),k+="c_t="+E(g));return k},buildImpressionRequestParams:function(a,d,f){a="c_n="+E(a)+"&c_p="+E(d);f&&(a+="&c_t="+E(f));return a},buildContentBlock:function(a){if(a){var d=
this.findContentName(a),f=this.findContentPiece(a);a=this.findContentTarget(a);d=d?this.trim(d):"Unknown";f=f?this.trim(f):"Unknown";a=a?this.trim(a):"";return{name:d,piece:f,target:a}}},collectContent:function(a){if(null===a||void 0===a||!a.length)return[];var d=[],f;for(f=0;f<a.length;f++){var g=this.buildContentBlock(a[f]);x(g)&&d.push(g)}return d},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||A.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?
":"+a.port:""));return a},toAbsoluteUrl:function(a){var d;return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+((null===(d=/(.*\/)/.exec(this.getLocation().pathname))||void 0===d?void 0:d[0])||"")+a:a},isUrlToCurrentDomain:function(a){a=
this.toAbsoluteUrl(a);if(!a)return!1;var d=this.getLocation().origin;return d===a?!0:0===String(a).indexOf(d)?":"===String(a).substr(d.length,1)?!1:!0:!1},setHrefAttribute:function(a,d){a&&d&&u.setAnyAttribute(a,"href",d)},shouldIgnoreInteraction:function(a){var d=u.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=u.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return d||a}},cd="addTracker setTrackingSourceProvider disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints setUserIsAnonymous".split(" "),
zd=["trackError"];X(A,"beforeunload",function(){for(var a=W,d=eb,f=0;f<a.length;f+=1)a[f].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<fc.length;a+=1)fc[a].trackHeartBeat({lastHeartbeat:!0});if(d){do a=new Date;while(a.getTime()<d)}},!1);var ec={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,d,f,g){"undefined"===P(g)&&(g=!1);X(a,d,f,g)},onLoad:Aa,onReady:Oa,isNodeVisible:yb,isOrWasNodeVisible:B.isNodeVisible},on:function(a,d){fa[a]||(fa[a]=[]);fa[a].push(d)},off:function(a,d){if(fa[a]){var f=
0;for(f;f<fa[a].length;f++)fa[a][f]===d&&fa[a].splice(f,1)}},trigger:function(a,d,f){if(fa[a]){var g=0;for(g;g<fa[a].length;g++)fa[a][g].apply(f||A,d)}},getTracker:function(a,d){x(d)||(d=this.getAsyncTracker().getSiteId());x(a)||(a=this.getAsyncTracker().getTrackerUrl());var f=new Cb(a,d);fc.push(f);return f},getAsyncTrackers:function(){return W},addTracker:function(a,d){return W.length?W[0].addTracker(a,d):bd(a,d)},getAsyncTracker:function(a,d){if(W[0])var f=W[0];else return bd(a,d);if(!d&&!a)return f;
x(d)&&null!==d||(d=f.getSiteId());x(a)&&null!==a||(a=f.getTrackerUrl());var g=0;for(g;g<W.length;g++)if(f=W[g],String(f.getSiteId())===String(d)&&f.getTrackerUrl()===a)return f}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return ec});var Cd=ec;"object"!==P(window[I.queueName])&&(window[I.queueName]=[]);"object"!==P(window[I.objectName])&&(window[I.objectName]=Cd);(function(){window[I.objectName].getAsyncTrackers().length?F("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):
("object"!==P(window[I.queueName])||"undefined"===P(window[I.queueName].length)?0:window[I.queueName].length)?window[I.objectName].addTracker():window[I.queueName]={push:function(a){F(I.queueName+".push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.",
a)}};window[I.objectName].trigger("PiwikInitialized",[]);window[I.objectName].initialized=!0})();"undefined"===P(window.AnalyticsTracker)&&(window.AnalyticsTracker=window[I.objectName]);"function"!==typeof window[I.objectName].piwik_log&&(window.piwik_log=Ad)})()
//# sourceMappingURL=ppms.js.map
